steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/locutus-407820/locutus', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/locutus-407820/locutus']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'locutus', '--image', 'gcr.io/locutus-407820/locutus', '--region', 'us-central1']
images:
- gcr.io/locutus-407820/locutus