from typing import Any

from marshmallow import Schema, fields, post_load

from locutus.model.harmony_export import (
    HarmonyBase,
    HarmonyFormat,
    HarmonyOutputFormat,
    basic_date,
)
from locutus.model.harmony_export import harmony_exporter as build_harmony_exporter
from locutus.model.reference import Reference
from locutus.model.visibility import Visibility

from .serializable import Serializable

"""
A data-dictionary is a collection of tables that, together, describe the 
complete data format for a study's datasets. 

Id:
This should be generated by the system, but can be provided by the user. 

Name (required):
A Human friendly name associated with the data-dictionary. 

Description:
An optional block of text that is used to provide context for understanding the
data-dictionary's purpose.

Tables:
references to the various tables that comprise the data-dictionary


"""


class DataDictionary(Serializable):
    _id_prefix = "dd"

    def __init__(
        self,
        id: str | None = None,
        _id: Any = None,
        name: str | None = None,
        description: str | None = None,
        tables: list[dict] | None = None,
        resource_type: str | None = None,
        owner_id: str | None = None,
        visibility: Visibility = Visibility.Registered,
        access: dict | None = None,
    ):
        super().__init__(
            id,
            _id=_id,
            collection_type="DataDictionary",
            resource_type="DataDictionary",
        )
        self.id = id
        self.name = name
        self.description = description

        # Access-control fields (Auth Requirements M4) -- see the same note
        # in model/study.py.
        self.owner_id = owner_id
        self.visibility = visibility
        self.access = (
            access if access is not None else {"institutions": {}, "users": {}}
        )

        self.tables = []
        super().identify()

        if tables is not None:
            for t in tables:
                self.tables.append(Reference(reference=t["reference"]))

    def remove_table(self, table_id: str) -> int:
        matching_references = []

        treference = f"Table/{table_id}"

        for idx, tblref in enumerate(self.tables):
            if tblref.reference == treference:
                matching_references.append(idx)

        if len(matching_references) > 0:
            for ref in matching_references:
                del self.tables[ref]

        return len(matching_references)

    def keys(self) -> list[str | None]:
        return [self.name]

    def as_harmony(
        self,
        harmony_exporter: HarmonyBase | None = None,
        harmony_format: HarmonyFormat = HarmonyFormat.Whistle,
        harmony_output_format: HarmonyOutputFormat = HarmonyOutputFormat.JSON,
        **kwargs,
    ) -> list:

        if kwargs.get("version") is None:
            kwargs["version"] = basic_date()

        if harmony_exporter is None:
            harmony_exporter = build_harmony_exporter(
                harmony_format=harmony_format, output_format=harmony_output_format
            )

        total_mappings = []
        for table in self.tables:
            total_mappings += table.dereference().as_harmony(
                harmony_exporter=harmony_exporter,
                dd_name=self.name,
                dd_id=self.id,
                **kwargs,
            )

        return total_mappings

    class _Schema(Schema):
        id = fields.Str()
        name = fields.Str(required=True)
        description = fields.Str()
        owner_id = fields.Str(allow_none=True)
        visibility = fields.Str()
        access = fields.Dict()

        tables = fields.List(fields.Nested(Reference._Schema))
        resource_type = fields.Str()

        @post_load
        def build_terminology(self, data: dict, **kwargs) -> "DataDictionary":
            return DataDictionary(**data)
