from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any, cast

from marshmallow import Schema, fields, post_load

import locutus
from locutus.model.exceptions import CodeAlreadyPresent
from locutus.model.harmony_export import (
    HarmonyBase,
    HarmonyFormat,
    HarmonyOutputFormat,
    basic_date,
)
from locutus.model.harmony_export import harmony_exporter as build_harmony_exporter
from locutus.model.provenance import Provenance
from locutus.model.reference import Reference
from locutus.model.terminology import Terminology
from locutus.model.variable import Variable
from locutus.model.visibility import Visibility

if TYPE_CHECKING:
    # Coding/CodingMapping are only needed for annotations here -- a real
    # top-level import creates a circular import (table -> coding ->
    # lookups -> terminology -> coding, initialized mid-way through).
    from locutus.model.coding import Coding, CodingMapping

from . import Serializable

logger = logging.getLogger(__name__)

"""
A Table represents a collection of dataset "variables", typically organized
as a list, such as one might find inside a CSV file.

Tables will exist in their own collection and have an id which can be used to
reference them from within a data-dictionary.

Id:
This should be generated by the system, but can be provided by the user.

Name (required):
A Human friendly name associated with the table.

URL (required):
The table's "system" identifier.

filename:
This is a bit of a relic that is used to refer back to the initial source from
which the table was defined.

Description:
An optional block of text that is used to provide context for understanding the
table's purpose.


Shadow Terminology: Each table must have a terminology which reflects each of
variables in the table as terms. This terminology must be changed to reflect
the table with any changes.
"""


class Table(Serializable):
    _id_prefix = "tb"

    def __init__(
        self,
        id: str | None = None,
        _id: Any = None,
        code: str = "",
        name: str | None = None,
        url: str | None = None,
        description: str | None = None,
        filename: str | None = None,
        variables: list[dict] | None = None,
        terminology: dict | None = None,
        resource_type: str = "Table",
        editor: str | None = None,
        owner_id: str | None = None,
        visibility: Visibility = Visibility.Registered,
        access: dict | None = None,
    ):
        if variables is None:
            variables = []
        logger.info(f"Creating new table: id={id}:_id={_id}")
        super().__init__(id=id, _id=_id, collection_type="Table", resource_type="Table")
        logger.info(f"Table created: id={self.id}")

        if locutus.strip_none(code) == "":
            code = locutus.strip_none(name)

        self.id = id
        self.name = name
        self.code = code
        self.description = description
        self.filename = filename
        self.url = url
        self.variables = []
        self._terminology = None

        # Access-control fields (Auth Requirements M4) -- see the same note
        # in model/study.py.
        self.owner_id = owner_id
        self.visibility = visibility
        self.access = (
            access if access is not None else {"institutions": {}, "users": {}}
        )

        # For the time being, since old tables don't have them, we must create
        # the shadow terminologies on the fly. If we do this, we need to save
        # the table, but only after we've repopulated it with the corresponding
        # variables.
        added_terminology = False

        # This represents the "shadow" terminology that reflects the variable
        # names and descriptions associated with a given table.
        if terminology:
            logger.info(f"Table reusing terminology: {terminology['reference']}")
            self.terminology = Reference(reference=terminology["reference"])
        else:
            terminology = {
                "name": name,
                "url": f"{url}/{name}",
                "description": self.description,
                "codes": [],
            }

            logger.info(f"Instantiating new terminology {terminology}")
            t = Terminology(**terminology)
            logger.info(f"Saving Table {name}")
            t.save()
            logger.info("Saved Completed")
            print(
                f"Creating Shadow Terminology for table: {self.name} -- Terminology ID: {t.id}"
            )
            self.terminology = Reference(f"Terminology/{t.id}", t)
            added_terminology = True

        for var in variables:
            # We definitely don't want to add provenance when we are reloading resources from the database
            self.add_variable(var, editor=editor)

        super().identify()

        if added_terminology:
            self.save()

    def remove_variable(self, varname: str, editor: str | None) -> None:
        success = False
        varname = locutus.normalize_ftd_placeholders(varname)

        for var in self.variables:
            if var.name == varname:
                # TODO: How to handle deleting enumerated variables tables
                # For now, I am not willing to handle enumerated variables
                # differently, since it could result in unwittingly deleting
                # something that is intended to remain. That is something
                # real to address, though.
                print(f"Removing variable '{varname}' from {self.name}.")
                self.variables.remove(var)
                self.terminology.dereference().remove_code(code=var.code, editor=editor)
                success = True
                return
        if not success:
            msg = f"The table, '{self.name}' ({self.id}), has no code, '{varname}'"
            print(msg)
            raise KeyError(msg)

    def rename_var(
        self,
        original_varname: str,
        new_varname: str,
        new_description: str | None,
        editor: str | None,
    ) -> bool:
        # Ensure codes are not placeholders at this point.
        original_varname = locutus.normalize_ftd_placeholders(original_varname)

        new_varname = locutus.normalize_ftd_placeholders(new_varname)

        print(
            f"Renaming Variable, {original_varname} to {new_varname} with new desc: {new_description}"
        )
        old_values = []
        new_values = []

        terms = self.terminology.dereference()
        for var in self.variables:
            # print(f"{self.name} - {var.name} == {original_varname}")
            if var.name == original_varname:
                original_code = var.code

                # It's not unreasonable we have only been asked to update the
                # display, so no need to wastefully change all of the details
                # about the code when the end result is the same
                if original_varname != new_varname:
                    old_values.append(f"variable: {original_varname}")
                    new_values.append(f"variable: {new_varname}")
                    var.name = new_varname
                    var.code = new_varname
                    if var.code != original_code:
                        # Since we found a matching code, we'll pull the mappings and
                        # save those under the new code after deleting the old ones.

                        mappings = terms.mappings(original_code)
                        if original_code in mappings and mappings[original_code] != []:
                            terms.set_mapping(
                                var.code, mappings[original_code], editor=editor
                            )
                            terms.delete_mappings(code=original_code, editor=editor)

                if new_description is not None:
                    old_values.append(f"description: {var.description}")
                    new_values.append(f"description: {new_description}")
                    var.description = new_description

                old_values = ",".join(old_values)
                new_values = ",".join(new_values)

                self.save()
                if new_values:
                    terminology = self.terminology.dereference()
                    terminology.add_provenance(
                        change_type=Provenance.ChangeType.EditTerm,
                        target=original_code,
                        old_value=old_values,
                        new_value=new_values,
                        editor=editor,
                    )
                    terminology.add_provenance(
                        change_type=Provenance.ChangeType.EditTerm,
                        target="self",
                        old_value=old_values,
                        new_value=new_values,
                        editor=editor,
                    )
                    if original_varname != new_varname:
                        for prov in Provenance.mapping_provenance(
                            terminology_id=self.id,
                            target_coding=original_varname,
                            return_instance=True,
                        ):
                            prov.target_coding = new_varname
                            prov.save()
                return True
        return False

    def get_variable(self, code_or_var: str) -> Variable | None:
        # We'll preference the code, but if none match at the code level, then
        # we match on name, or return None

        var_of_interest = None

        for var in self.variables:
            if var.code == code_or_var:
                var_of_interest = var
                break

        if var_of_interest is None:
            for var in self.variables:
                if var.name == code_or_var:
                    var_of_interest = var
                    break
        return var_of_interest

    def _insert_variable(self, variable: Variable) -> bool | None:
        """If aa variable with the same name exists, replace it. Else append"""

        for idx, var in enumerate(self.variables):
            if variable.name == var.name:
                self.variables[idx] = variable
                return True
        self.variables.append(variable)

    def add_variable(self, variable: dict, editor: str | None = None) -> None:
        v = variable

        # Ensure the name is not a ftd_placeholder
        v["name"] = locutus.normalize_ftd_placeholders(v["name"])

        if type(variable) is dict:
            # For now, let's insure that the enumerations terminology is there or
            # create an empty one if not. This may need to be moved into the
            # variable itself.

            if v["data_type"] == "ENUMERATION" and (
                "enumerations" not in v or len(v["enumerations"]) < 1
            ):
                # Create an empty terminology and create a reference to that
                # terminology
                t = Terminology(
                    name=v["name"],
                    description=v.get("description"),
                    url=f"{self.url}/{v['name']}",
                )
                t.save()

                reference = f"Terminology/{t.id}"
                v["enumerations"] = {"reference": reference}

            v = Variable.deserialize(variable)
            self._insert_variable(v)
        else:
            # Dead in practice -- every real caller passes a dict, so this
            # branch would already have crashed on `v["name"] = ...` above
            # before reaching here. See issues/033.
            v = cast(Variable, variable)
            self._insert_variable(v)

        try:
            self.terminology.dereference().add_code(
                code=v.code, display=v.name, editor=editor
            )
        except CodeAlreadyPresent:
            pass

    def build_harmony_row(
        self,
        local_coding: Coding,
        mapped_coding: CodingMapping,
        harmony_exporter: HarmonyBase,
        **kwargs,
    ):
        # id is always set by Serializable.identify() before any instance
        # method can run; name is required at the schema/API boundary
        # (fields.Str(required=True)) even though the attribute itself
        # allows None for a Table built directly in Python.
        return harmony_exporter.add_row(
            table_id=cast(str, self.id),
            source_text=local_coding.code,
            source_description=local_coding.display,
            source_domain=cast(str, self.name),
            parent_varname="",  # I'm not sure if we can get this ATM
            source_system=local_coding.system,
            mapping_relationship=mapped_coding.mapping_relationship,
            mapped_code=mapped_coding.code,
            mapped_display=mapped_coding.display,
            mapped_system=mapped_coding.system,
            comment="",
            **kwargs,
        )

    def harmonize_mappings(
        self,
        codings: dict,
        mappings: dict,
        harmony_mappings: list,
        harmony_exporter: HarmonyBase,
        var_name: str | None = None,
        **kwargs,
    ) -> None:

        for code, mapped_codings in mappings.items():
            if code not in codings:
                allowed_codes = "'" + "','".join(codings.keys()) + "'"
                print(
                    f"WARNING: The code, {code}, from variable, {self.name}:{var_name}, doesn't match any of the available codes: {allowed_codes}\n"
                )
            else:
                coding = codings[code]

                for mc in mapped_codings:
                    harmony_row = self.build_harmony_row(
                        coding, mc, harmony_exporter, **kwargs
                    )
                    if harmony_row is not None:
                        harmony_mappings += harmony_row

    def as_harmony(
        self,
        harmony_exporter: HarmonyBase | None = None,
        harmony_format: HarmonyFormat = HarmonyFormat.Whistle,
        harmony_output_format: HarmonyOutputFormat = HarmonyOutputFormat.JSON,
        **kwargs,
    ) -> list:

        if kwargs.get("version") is None:
            kwargs["version"] = basic_date()

        if harmony_exporter is None:
            harmony_exporter = build_harmony_exporter(
                harmony_format=harmony_format, output_format=harmony_output_format
            )

        # Iterate over each table
        harmony_mappings = []

        if self.terminology is not None:
            shadow = self.terminology.dereference()
            table_mappings = shadow.mappings()
            table_codings = shadow.build_code_dict()
            self.harmonize_mappings(
                codings=table_codings,
                mappings=table_mappings,
                harmony_mappings=harmony_mappings,
                harmony_exporter=harmony_exporter,
                **kwargs,
            )
        for var in self.variables:
            if var.data_type == Variable.DataType.ENUMERATION:
                term = var.get_terminology()

                # Capture a dictionary with code=>coding
                codings = term.build_code_dict()
                mappings = var.get_mappings()
                self.harmonize_mappings(
                    codings=codings,
                    mappings=mappings,
                    harmony_mappings=harmony_mappings,
                    var_name=var.name,
                    harmony_exporter=harmony_exporter,
                    **kwargs,
                )
        return harmony_mappings

    def keys(self) -> list[str | None]:
        return [self.url, self.name]

    def get_preference(self, code: str | None = None):
        """Retrieve preferences from the terminology or fall back to table
        preferences if none are found.

        If no VALID code is provided: returns Table preferences
        If code is provided, and preferences exist: returns the Code preferences.
        If code is provided, and no prefs exist: ruturns Table preferences.
        """
        try:
            pref = self.terminology.dereference().get_preference(code=code)

            # If code exists as a key and is empty get the Table preferences.
            if code in pref and not pref[code]["api_preference"]:
                table_pref = self.terminology.dereference().get_preference(code="self")
                return table_pref if table_pref else {}

            return pref

        except Exception as e:
            print(f"An error occurred while retrieving preferences: {e!s}")
            raise

    def add_or_update_pref(self, api_preference, code: str | None = None) -> None:
        try:
            self.terminology.dereference().add_or_update_pref(
                api_preference=api_preference, code=code
            )

        except Exception as e:
            print(f"An error occurred while updating preferences: {e!s}")
            raise

    def remove_pref(self, code: str | None = None):
        try:
            message = self.terminology.dereference().remove_pref(code=code)
            return message
        except Exception as e:
            print(f"An error occurred while updating preferences: {e!s}")
            raise

    def get_preferred_terminology(self):
        """
        Retrieves all references from the 'preferred_terminology' sub-collection

        Returns:
            list: 'references" - An array of `Terminology` reference dictionaries

        Example output:
        {
            "references": [
                {
                    "reference": "Terminology/tm--example1"
                },
                {
                    "reference": "Terminology/tm--example2"
                }
            ]
        }
        """
        try:
            pref = self.terminology.dereference().get_preferred_terminology()

            return pref

        except Exception as e:
            print(f"An error occurred while retrieving preferred terminology: {e}")
            raise

    def replace_preferred_terminology(
        self, editor: str | None, preferred_terminology: list
    ) -> None:
        """
        Creates or replaces a document in the 'preferred_terminology' sub-collection

        Args:
            preferred_terminology (list): A dictionary representing the preferred terminology to be added.

        JSON body with two additions example:
        [
            {
                "preferred_terminology": "tm--example1"
            },
            {
                "preferred_terminology": "tm--example2"
            }
        ]
        """
        try:
            self.terminology.dereference().replace_preferred_terminology(
                editor, preferred_terminology
            )

        except Exception as e:
            print(f"An error occurred while updating preferences: {e!s}")
            raise

    def remove_preferred_terminology(self):
        """
        Creates or replaces a document in the 'preferred_terminology' sub-collection

        Args:
            preferred_terminology (list): A dictionary representing the preferred terminology to be added.

        JSON body with two additions example:
        [
            {
                "preferred_terminology": "tm--example1"
            },
            {
                "preferred_terminology": "tm--example2"
            }
        ]
        """
        try:
            self.terminology.dereference().remove_preferred_terminology()

        except Exception as e:
            print(f"An error occurred while updating preferences: {e!s}")
            raise

    class _Schema(Schema):
        id = fields.Str()
        code = fields.Str()
        name = fields.Str(required=True)
        url = fields.URL(required=True)
        filename = fields.Str()
        description = fields.Str()
        variables = fields.List(fields.Nested(Variable._Schema))
        resource_type = fields.Str()
        terminology = fields.Nested(Reference._Schema)
        owner_id = fields.Str(allow_none=True)
        visibility = fields.Str()
        access = fields.Dict()

        @post_load
        def build_terminology(self, data: dict, **kwargs) -> Table:
            return Table(**data)

    def dump(self) -> dict:
        content = self.__class__._get_schema().dump(self)
        content["variables"] = [v.dump() for v in self.variables]

        return content
