# On PR merge(`main` into `release`):
#  * Publish `release` to GCP - prod

# On workflow dispatch:
#   * Publish `release` to GCP - prod

name: prod-flow

on:
  pull_request:
    branches:
      - release
    types:
      - closed

  workflow_dispatch:
    inputs:
      confirm:
        description: 'Are you sure you want to deploy to QA?'
        required: true
        default: 'n'
        type: choice
        options:
          - y
          - n
      
jobs:

  deploy-to-gcp-prod:
    runs-on: ubuntu-latest
    # Continue if the PR was merged in or if manually triggered(on purpose). 
    if: github.event.pull_request.merged == true || github.event.inputs.confirm == 'y'

    env:
      GCP_PROJECT_ID: ${{ secrets.PROD_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.PROD_SA_KEY }}
      IMAGE_NAME: locu_prod_img
      SERVICE_NAME: locu_prod
      REGION: ${{ secrets.REGION_LOC_1 }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}

      - name: Trigger Cloud Build
        uses: google-github-actions/deploy-cloudbuild@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          credentials: ${{ env.GCP_SA_KEY }}
          config: 'cloudbuild.yaml' 
          substitutions: PROJECT_ID=${{ env.GCP_PROJECT_ID }},IMAGE_NAME=${{ env.IMAGE_NAME }},SERVICE_NAME=${{ env.SERVICE_NAME }},REGION=${{ env.REGION }}
