name: dev-flow

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, edited, synchronize]

      
jobs:
  deploy-to-gcp-dev:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.DEV_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.DEV_SA_KEY }}
      IMAGE_NAME: locu_dev_img
      SERVICE_NAME: locu_dev
      REGION: ${{ secrets.REGION_LOC_1 }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}

      - name: Trigger Cloud Build
        uses: google-github-actions/create-cloud-deploy-release@v1.1.2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          credentials: ${{ env.GCP_SA_KEY }}
          config: 'cloudbuild.yaml' 
          substitutions: PROJECT_ID=${{ env.GCP_PROJECT_ID }},IMAGE_NAME=${{ env.IMAGE_NAME }},SERVICE_NAME=${{ env.SERVICE_NAME }},REGION=${{ env.REGION }}
