# On PR creation(`main` requesting to merge into `release`):
#  * Publish `main` to GCP - QA

# On workflow dispatch:
#   * Publish `main` to GCP - QA

name: qa-flow

on:
  pull_request:
    branches:
      - release
    types:
      - opened

  workflow_dispatch:
    inputs:
      confirm:
        description: 'Are you sure you want to deploy to QA?'
        required: true
        default: 'n'
        type: choice
        options:
          - y
          - n
      
jobs:

  deploy-to-gcp-qa:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.QA_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.QA_SA_KEY }}
      IMAGE_NAME: locu_qa_img
      SERVICE_NAME: locu_qa
      REGION: ${{ secrets.REGION_LOC_1 }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}

      - name: Trigger Cloud Build
        uses: google-github-actions/deploy-cloudbuild@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          credentials: ${{ env.GCP_SA_KEY }}
          config: 'cloudbuild.yaml' 
          substitutions: PROJECT_ID=${{ env.GCP_PROJECT_ID }},IMAGE_NAME=${{ env.IMAGE_NAME }},SERVICE_NAME=${{ env.SERVICE_NAME }},REGION=${{ env.REGION }}
